#!/bin/sh

PAGER=

cd dotfiles || exit

for file in $(git ls-tree -r --name-only HEAD)
do
	git diff --exit-code $file ~/$file

	if [ $? -ne 0 ]
	then
		printf "update [y/N]? "
		
		read -r a

		if echo $a | grep -q "^\(y\|Y\)\(es\?\)\?\$"
		then
			git diff --src-prefix=a/a/ $file ~/$file |
				git -C ../ apply -p 3 --directory=dotfiles/ -
		fi
	fi
done
