#!/bin/sh

# if you don't want all the files better to just ln -s them in ~/.xinitrc.d/ and chmod u+x

if [ -d /etc/X11/xinit/xinitrc.d ]
then
 	for x in /etc/X11/xinit/xinitrc.d/*
	do
		[ -x "$x" ] && . "$x"
	done
	unset x
fi

