#!/bin/sh

while sleep .25
do
	## pretty dumb
	playing=$(
		mpc -f "%artist% -> %album%\[%track%\] -> %title%" |
		head -n 2 |
		tac |
		tr -d '\n' |
		sed 's/^\[playing\] //'
	)

	xsetroot -name "[ $playing ] | [ $(date) ]"
done &
