#!/bin/sh

RC="$HOME/.shell"

[ -z "$PREFIX" ] && PREFIX="$RC"

IFS=":"
for i in $PATH
do
	if [ "$i" -eq "$PREFIX" ]
	then
		break
	fi
done
unset IFS

if [ -z "$i" ]
then
	export PATH="$PREFIX/bin:$PATH"
fi

#clones:

which() {
	$RC/src/which $@ > /dev/null 2>&1
	return $?
}

if ! which which
then
	ln -s "$RC/src/which" "$PREFIX/bin/which"
fi

if ! which rename
then
	ln -s "$RC/src/rename" "$PREFIX/bin/rename"
fi

if ! which readlink
then
	ln -s "$RC/src/readlink" "$PREFIX/bin/readlink"
fi

#extensions:
ln -s "$RC/src/rmdir" "$PREFIX/bin/rmdir"
ln -s "$RC/src/mv" "$PREFIX/bin/mv"

for i in $(ls -1 "$RC/init/")
do
	source "$RC/$i"
done
