#!/bin/sh
#
# gread
#
# Read input into variables based on regexp pattern groups
#
# USAGE
#
# gread PATTERN [var ...]
#
# Where PATTERN is a perl regular expression and var is a
# variable to be set to the first group matched, and so forth.
# If var is not supplied gread will print the captured groups.
#
# EXAMPLE
#
# 	echo -e "ab\ncd" | while gread "(.)(.)" foo bar
# 	do
# 		echo "foo: $foo, bar: $bar"
# 		...
# 	done
#
# Would output:
# 	foo: a, bar: b
# 	foo: c, bar: d
#
# NOTES
#
# * Group and argument count mismatches should behave in
# exactly the same way as read(1p)
#

gread() {
	[ $# -eq 0 ] && return 1

	if [ $# -eq 1 ]
	then
		_gread $1
	else
		read -r $(shift; echo $@) <<EOF
			$(_gread $1)
EOF
	fi
}
