#!/bin/sh

alias gdb="gdb -q"

alias nrep="grep -n"
alias qrep="grep -q"

alias ls="ls -F --color=always"

alias mpc='mpc -f "[%position%]: %file%"'

alias ffprobe='ffprobe -hide_banner'
alias ffmpeg='ffmpeg -hide_banner'

alias youtube-dl='youtube-dl --no-mtime'
